# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: mysql2 # replace with remote db type if different
  encoding: utf8 # modify if it is different
  reconnect: false
  database: fmates_tracemates_staging_v1_db
  pool: 5
  username: fmates_tracemate
  password: tr^c3m^t3s
  host: foodmates.dedicated.co.za

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: trace_mates_test
  pool: 5
  username: root
  password: hackmyAss10_
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2 # replace with remote db type if different
  encoding: utf8 # modify if it is different
  reconnect: false
  database: fmates_tracemates_production
  pool: 5
  username: fmates_tracemate
  password: tr^c3m^t3s
  host: foodmates.dedicated.co.za

foodmates_cpanel:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: fmates_tracemates_staging_v1_db
  pool: 5
  username: fmates_tracemate
  password: tr^c3m^t3s
  #socket: /var/run/mysqld/mysqld.sock
  #port: 3306
  host: 197.242.158.23