# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: trace_mates_dev
  pool: 5
  username: root
  password: hackmyAss10_
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: trace_mates_test
  pool: 5
  username: root
  password: hackmyAss10_
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: trace_mates_production
  pool: 5
  username: root
  password: hackmyAss10_
  socket: /var/run/mysqld/mysqld.sock               
